{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
{{- with .Values.secrets.annotations }}
  annotations: {{- toYaml . | nindent 4 }}
{{- end }}
  name: {{ include "seleniumGrid.common.secrets.fullname" . }}
  labels:
    {{- include "seleniumGrid.commonLabels" . | nindent 4 }}
    {{- with .Values.customLabels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
type: Opaque
data:
{{- range $name, $value := .Values.secrets.env }}
{{- if not (empty $value) }}
  {{- $_ := set $ "name" $name }}
  {{- $_ := set $ "value" $value }}
  {{ $name }}: {{ tpl ($value) $ | b64enc }}
{{- end }}
{{- end }}
{{- if eq .Values.basicAuth.enabled true }}
  ROUTER_USERNAME: {{ .Values.basicAuth.username | b64enc }}
  ROUTER_PASSWORD: {{ .Values.basicAuth.password | b64enc }}
{{- end }}
{{- if .Values.tls.enabled }}
  SE_JAVA_SSL_TRUST_STORE_PASSWORD: {{ .Values.tls.trustStorePassword | b64enc }}
{{- end }}
{{- if (include "seleniumGrid.tls.registrationSecret.enabled" $) }}
  SE_REGISTRATION_SECRET: {{ .Values.tls.registrationSecret.value | b64enc }}
{{- end }}
{{- if .Values.videoRecorder.uploader.secrets }}
{{- range $name, $value := .Values.videoRecorder.uploader.secrets }}
{{- if not (empty $value) }}
  {{ $name }}: {{ tpl ($value) $ | b64enc }}
{{- end }}
{{- end }}
{{- end }}
{{- if and .Values.videoRecorder.uploader.enabled }}
{{- range $fileName, $value := .Values.uploaderConfigMap.secretFiles }}
{{- if not (empty $value) }}
  {{ $fileName }}: {{ $value | b64enc }}
{{- else }}
{{- $files := $.Files.Glob (printf "configs/uploader/%s/%s" $.Values.videoRecorder.uploader.name $fileName) }}
{{- $cfg := $files.AsSecrets }}
{{- if and (gt (len $files) 0) (ne $cfg "") }}
{{ indent 2 $cfg }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
